version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crawler
