import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import axios from "axios";
import useStep from "../hooks/useStep";
import type { Post } from "../type";
import { PageLayout } from "@components/Layout";
import { Card } from "@components/Card";
import { Posts } from "@components/Posts";
import { Paginator } from "@components/Paginator";
import { Center, Text } from "@chakra-ui/react";
import { ThreeCircles } from "react-loader-spinner";
const Home: NextPage = () => {
  const pages = 25;
  const [currentStep, helpers] = useStep(pages);

  const [posts, setPosts] = React.useState<Post[]>([]);
  const [isLoading, setLoading] = React.useState(true);

  React.useEffect(() => {
    setLoading(true);
    const url = `http://localhost:3001/posts?page=${currentStep}`;
    const data = axios.get(url);
    data.then((res) => {
      setPosts(res.data.posts);
      // Used timeout here just to see the spinner.
      setTimeout(() => setLoading(false), 500);
    });
  }, [currentStep]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        {isLoading ? (
          <Center h="90vh">
            <ThreeCircles
              height="180"
              width="180"
              color="#ED2B2A"
              wrapperStyle={{}}
              wrapperClass=""
              visible={true}
              ariaLabel="three-circles-rotating"
            />
          </Center>
        ) : (
          <Posts posts={posts} />
        )}
        {!posts && <Text> No posts found ...</Text>}
        <Paginator
          maxPages={pages}
          helpers={helpers}
          currentPage={currentStep}
        />
      </PageLayout>
    </div>
  );
};

export default Home;

